name = "TypeSpec"
grammar = "typespec"
path_suffixes = ["tsp"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
autoclose_before = ";:.,=}])>"
tab_size = 2
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = false, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "`", end = "`", close = true, newline = false, not_in = ["comment", "string"] },
]
